stages:

  data_ingestion:
    cmd: python src/bert_toxic_chat_clf/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bert_toxic_chat_clf/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs: 
      - artifacts/data_ingestion/data.csv

  data_split:
    cmd: python src/bert_toxic_chat_clf/pipeline/stage_02_data_split.py
    deps:
      - src/bert_toxic_chat_clf/pipeline/stage_02_data_split.py
      - config/config.yaml
    params:
      - TRAIN_SIZE
    outs:
      - artifacts/data_split/train/train.csv
      - artifacts/data_split/test/test.csv

  setup_model:
    cmd: python src/bert_toxic_chat_clf/pipeline/stage_03_setup_model.py
    deps:
      - src/bert_toxic_chat_clf/pipeline/stage_03_setup_model.py
      - config/config.yaml
    params:
      - CLASSES
      - DROPOUT
    outs:
      - artifacts/setup_model/model.pth
    
  train:
    cmd: python src/bert_toxic_chat_clf/pipeline/stage_04_train.py
    deps:
      - src/bert_toxic_chat_clf/pipeline/stage_04_train.py
      - config/config.yaml
      - artifacts/data_split/train/train.csv
      - artifacts/setup_model/model.pth
    params:
      - MAX_LEN
      - TRAIN_BATCH_SIZE
      - EPOCHS
      - LEARNING_RATE
      - TRAIN_NUM_WORKERS
      - TRAIN_SHUFFLE
    outs:
      - artifacts/training/model.pth
    
  evaluation:
    cmd: python src/bert_toxic_chat_clf/pipeline/stage_05_evaluation.py
    deps:
      - src/bert_toxic_chat_clf/pipeline/stage_04_train.py
      - config/config.yaml
      - artifacts/data_split/test/test.csv
      - artifacts/training/model.pth
      - params.yaml

    metrics:
    - scores.json:
        cache: false

