# setup-model
CLASSES: 3
DROPOUT: 0.3

# split
TRAIN_SIZE: 0.7

# training
MAX_LEN: 200
TRAIN_BATCH_SIZE: 8
TRAIN_SHUFFLE: True
TRAIN_NUM_WORKERS: 0
EPOCHS: 1
LEARNING_RATE: 0.01

# validation
VALID_NUM_WORKERS: 0
VALID_SHUFFLE: True
VALID_BATCH_SIZE: 4