# setup-model
CLASSES: 3
DROPOUT: 0.3

# training
TRAIN_SIZE: 0.8
MAX_LEN: 200
TRAIN_BATCH_SIZE: 8
VALID_BATCH_SIZE: 4
EPOCHS: 1
LEARNING_RATE: 0.00001
TRAIN_NUM_WORKERS: 0
VALID_NUM_WORKERS: 0
TRAIN_SHUFFLE: True
VALID_SHUFFLE: True

